### ISSUE TITLE
Cancel OpenDEX orders when connectivity to Exchange is lost

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/market-maker-tools#2]
**If our connection with exchange goes offline/becomes unresponsive**, arby should cancel open OpenDEX orders. This is important, because otherwise xud could swap orders on OpenDEX, where the bot is unable to do the counter trade on e.g. Binance for.

**Comment by erkarl** [comment]
Just to clarify - this issue is now about when we lose connectivity to the centralized exchange. Arby must cancel all orders on OpenDEX and resume normal operations only when connectivity has been restored.

**Comment by kilrau** [comment]
Adjusted description.

xud <-> arby connection loss needs separae issue.
