### ISSUE TITLE
Add all params(that were used for arby run) printing to arby log

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/market-maker-tools#35]
Add all params(that were used for arby run) printing to arby log (except of binance creds) like it was made for xud.
![Screenshot from 2020-06-23 19-27-48](https://user-images.githubusercontent.com/29906866/85429967-2b02b980-b588-11ea-8f1f-d19dabb00915.png)

**Comment by erkarl** [comment]
Should already be implemented.
