### ISSUE TITLE
Logics of Arby

### ISSUE THREAD

**Issue by xVETTEx** [ExchangeUnion/market-maker-tools#5]
We need logic written down clearly, so we can improve it. Also users probably want to see how arby works, before they start to use it.
There is something to open discussion.

**My propsal to logics:**
1. Arby check user's balances from used exchanges and OpenDEX
2. Decide orders that can be placed, depends about used pairs and balances. 
3. Place limit orders to opendex. 
4. Upgrade prices of opendex orders when price on exchange has moved out of moving area.

When opendex order is filled:
5. Market order to exchange is placed opposite side of filled order in opendex was with same amount that opendex order was.
6. When market order is excecuted, return to 3. (new order to opendex is placed for opposite side of market order on binance was, etc.)

**Formula for opendex order price:**
Moving area: amount that price can move on exchange before placing new order on OpenDEX.

Sell order's price on opendex: best buy order's price on exchange - lightning fee - exchange fee - arby commission - moving area.

Buy order's price on opendex: best sell order's price on exchange + lightning fee + exchange fee + arby commission + moving area.

**Some problems with this concept**:
1. If someone woud want earn more BTC or some specific currency with Arby, it may isn't possible now. User has hodl two or more currencies, and only one of these can be currency that user want earn. If Arby trade BTC/ETH pair, and price of ETH drop, even when there is commission, user could lose when all tokens is converted to BTC. Even more complicated is case if Arby trades some pair where isn't BTC (ETH/DAI, DAI/LTC, etc.).
2. Arby don't change balances avaible to trade in different pairs. This would be useful if there is open orders in OpenDEX that would be profitable, but Arby don't have balances in right pairs/currencies to take that order.
3. If on OpenDEX there is much profitable buy orders to LTC/BTC and no sell orders. When arby once claim buy orders, it has to wait until someone want sell with profitable price, before Arby can fill more buy orders.
4. This concept does not include about how much balance is traded/hold in specific pair or currency.

**Comment by erkarl** [comment]
Thanks for your proposals/ideas. This is a great starting point.

> We need logic written down clearly, so we can improve it. Also users probably want to see how arby works, before they start to use it.

You're absolutely right. I'm going to update the documentation this week that explains the current logic in detail.

**Comment by kilrau** [comment]
Does https://github.com/ExchangeUnion/market-maker-tools/pull/6 close this for you or do you think something else should be added? @xVETTEx

**Comment by kilrau** [comment]
Closing here, please open a new issue (or PR) for anything that is still missing.
