### ISSUE TITLE
Specify OpenDEX and CEX base asset and quote asset separately

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/market-maker-tools#95]
This issue is about allowing to specify CEX and OpenDEX assets separately in the configuration:

For example
```
OPENDEX_BASEASSET=BTC
OPENDEX_QUOTEASSET=USDT
CEX_BASEASSET=BTC
CEX_QUOTEASSET=USD
```

**Comment by kilrau** [comment]
This one is important, because e.g. Binance lists as USDT/DAI and Kraken as DAI/USDT.
