### ISSUE TITLE
Validate base and quote asset based on exchange's supported markets

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/market-maker-tools#99]
At the moment valid trading pairs are hardcoded in the configuration checks.

This issue is about fetching active markets for DEX and CEX and validating the provided trading pair against it.

**Comment by kilrau** [comment]
To add some more details:
> This issue is about fetching active markets for DEX and CEX and validating the provided trading pair against it.
Validating means, that if the configured quote & base asset is found on the CEX, arby will just use it. If it is not found, it will throw an error and shut down.

Additionally we want to make `cex-baseasset` & `cex-quoteasset` optional, since these values are only required if arby *cannot* find the pair on the exchange.

**Comment by kilrau** [comment]
Also `cex-base-asset` & `cex-quote-asset` should be ignored entirely if `test-centralized-baseasset-balance` & `test-centralized-quoteasset-balance` are set.

**Comment by erkarl** [comment]
> Also `cex-base-asset` & `cex-quote-asset` should be ignored entirely if `test-centralized-baseasset-balance` & `test-centralized-quoteasset-balance` are set, meaning arby doesn't even connect to a cex and to fetch markets/pairs.

How does arby get the price feed for CEX if `cex-base-asset` and `cex-quote-asset` values are ignored?

**Comment by kilrau** [comment]
Arby subscribes to the CEX price stream for `base-asset` and `quote-asset`

**Comment by erkarl** [comment]
> Arby subscribes to the CEX price stream for `base-asset` and `quote-asset`

Yes, arby subscribes to the price stream for `base-asset` and `quote-asset` (or `cex-base-asset` and `cex-quote-asset` if defined), but we should still validate that the trading pair exists on that CEX (otherwise we won't get a price feed). This should happen even if `test-centralized-baseasset-balance` and `test-centralized-quoteasset-balance` is defined.

**Comment by kilrau** [comment]
Agreed! My bad, removed that point.

**Comment by kilrau** [comment]
Closed by https://github.com/ExchangeUnion/market-maker-tools/pull/111
